databases:
  - name: euro_champ_2024
    databaseName: euro_champ_2024
    user: euro_champ_2024

services:
  - type: web
    name: euro_champ_2024
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: euro_champ_2024
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
